### ISSUE TITLE
Optional / required colors swapped in comparison diagram

### ISSUE THREAD

**Issue by hbruch** [MobilityData/gtfs-flex#13]
In the upper half (GTFS model) of the comparison chart, background colors for optional and required  files are swapped.

**Comment by antrim** [comment]
pinging @nihit-jain-ibigroup

**Comment by nihit-jain-ibigroup** [comment]
Thanks for the note Holger and Aaron! I will update the diagram.

**Comment by antrim** [comment]
@nihit-jain-ibigroup Hi Nihit, I wanted to ping on this and see if you have been able to update the diagram. Can you make a pull request?

**Comment by nihit-jain-ibigroup** [comment]
@antrim Sorry for the delay Antrim, I just updated it.

**Comment by barbeau** [comment]
Thanks Nihit!

On Dec 25, 2016 5:11 PM, "Nihit Jain" <notifications@github.com> wrote:

@antrim <https://github.com/antrim> Sorry for the delay Antrim, I just
updated it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CUTR-at-USF/gtfs-flex/issues/13#issuecomment-269139278>,
or mute the thread
