### ISSUE TITLE
DRT service w/o fixed boundaries (but with a center point)

### ISSUE THREAD

**Issue by antrim** [MobilityData/gtfs-flex#14]
Many taxis and hired car services may not have a fixed boundary of service. Instead, there is a generalized service area around a center point. See screenshot from Google Maps showing a Portland-area taxi company service area as an example.

Should we add a feature in GTFS-flex to define a service center point with radius?

![broadway cab](https://cloud.githubusercontent.com/assets/6495639/21379116/40cf8a9c-c700-11e6-8d7e-f6854aac9fee.png)

**Comment by barbeau** [comment]
Circles can be defined with the current area mechanism:
https://github.com/CUTR-at-USF/gtfs-flex/blob/master/spec/reference.md#defining-areas

...so I think the main question here is if defining shape types has more pros than cons - some thoughts below.

Pros:
* As a producer, easier to define a service area by hand - You can provide a point and radius and be done, rather than figuring out a way to generate all the points for the circle shape.  However, there are online tools to generate such points (see [this site](http://www.gpsvisualizer.com/calculators)).
* Helps avoid the "too many shape points" issue - If producer defines a circle with radius and point, there isn't the opportunity to provide too many points that are too close to one another.
* Potentially smaller feed files - Instead of defining many points for a circle, you could represent it with just radius and point.

Cons:
* Could potentially lead to less accurate service areas - producers could start preferring circles to polygons because they are easier to define.  As a result, consumers get less accurate zones of service.
* More complexity for consumers - consumers have to support multiple methods for rendering service areas, instead of just supporting polygons in general.

**Comment by antrim** [comment]
This counterpoint and discussion is helpful to refine my thinking.

I suppose there would be two separate purposes to using center points/radius instead of area:

1. Make it easier to write out a GTFS-flex dataset "by hand"
2. Express a service area boundary that is "fuzzy." The transportation provider focuses around their center of operations, but there is no fixed edge to the service area.

**Comment by antrim** [comment]
This counterpoint and discussion is helpful to refine my thinking.

I suppose there would be two separate purposes to using center points/radius instead of area:

1. Make it easier to write out a GTFS-flex dataset "by hand"
2. Express a service area boundary that is "fuzzy." The transportation provider focuses around their center of operations, but there is no fixed edge to the service area.

I realize now that I had conflated those two purposes together with one GTFS-flex feature here, so perhaps we should think about this a little more. Let's just keep this open as we collect example cases to work off of.
