### ISSUE TITLE
Service areas overlapping in time - in a single trip?

### ISSUE THREAD

**Issue by antrim** [MobilityData/gtfs-flex#21]
As written, the Spec would allow multiple service areas to be activated in a single "trip" at the same time. i.e. a record in stop_times.txt with start_service_area_id='AreaX' immediately followed by another record where start_service_area_id='AreaY'. We have not provided any examples of this in the draft spec.

Question: Are there indeed cases where it would be useful to have this capability?

* If so, then let's better define this.
* If not, then let's think about removing this capability/simplifying.

**Comment by thomastrillium** [comment]
If this is not useful/necessary, suggested change to spec:

Description of `start_service_area_id` changed to read--

Must be *immediately* followed by a corresponding stop-time entry in the trip with a matching end_service_area_id value.

**Comment by antrim** [comment]
Are there "zone-based" services where the area expands during particular service hours? IF these services exist, what are conventions around trips that start in one zone and end in another? Can pickup occur during the the service for only AREA A, with drop-off then occuring later in AREA B (as indicated below)?

![cross-area trips](https://cloud.githubusercontent.com/assets/6495639/25463382/aed5b1fc-2aaa-11e7-8d37-7d14d3dc9ca0.png)

Original Google Doc: https://docs.google.com/drawings/d/1Y7paHKIJHQ8VvNS2pfLdfLqWRsIfssV9XwwsYFYBI-Y/edit

**Comment by ed-g** [comment]
There is another option if we do not wish for multiple areas to be defined.

We can remove `start_service_area_id` and `end_service_area_id`, in favor of an `area_id` which is present at every stop-time entry where a transit vehicle may potentially pick-up or drop-off a passenger anywhere in the specified service area.

This mirrors the use of the `continuous_stops` field.

**Comment by ed-g** [comment]
Note that for every trip which can be expressed with multiple service areas A1, A2, A3  activated there is an equivalent trip which can be expressed as serving a single area M123 = A1+A2+A3 calculated as the geographical union of those multiple service areas.

So any multiple-service-areas format can be automatically converted into a single-service-area format which would function exactly the same way.

**Comment by PPaulsonOregonDOT** [comment]
I agree with ed here because it simplifies the database schema, and makes it more intuitive. Stop-times.txt tells you when a bus runs, and stops.txt and the added areas.txt describe where it run.

**Comment by thomastrillium** [comment]
I also am inclined to agree with Ed.

I think the original concept was that we might need to refer to multiple areas as active between two stop times.

- initial research indicated that this did result in an ambiguity in the spec, as well as duplicative entries in the stop_times.txt file
- we've not had anyone yet show a service where that was necessary
- Ed has noted that mathematically, we don't eliminate any functionality by preventing multiple areas, because a new "multi-area" can aways be defined that encompasses both areas that need to be referenced.

Unless any one debates the change, I'll submit a PR later this week that eliminates `start_service_area_id` and `end_service_area_id`, in favor of an `area_id` with a description like "When present, the area_id indicates a service area within which a route may deviate after serving the `stop_id` referenced in the same stop_times.txt entry.

Note that this has the (pleasant) side effect of implying why it is that we're still referencing a `stop_id` in these entries that reference an `area_id`. Instead of being a "dummy" stop referenced in the entry, the `stop_id` would now explicitly be a "starting point" for service of the area. This has some notable ramifications. For example, for a Dial-a-Ride service, this stop_id would now presumably be at the location where the vehicle is dispatched from, rather than an arbitrary point in the middle of the service area.

**Comment by creeplord** [comment]
Interested in GTFS flex I can provide data from my dial-a-ride program if it's helpful. Here's a pdf of all my annual trips from an address locator i create in ArcGIS. Service is located in New Jersey
[2016_Medical_GIS.pdf](https://github.com/CUTR-at-USF/gtfs-flex/files/2102322/2016_Medical_GIS.pdf)
[2016_Trips_Final_GIS.pdf](https://github.com/CUTR-at-USF/gtfs-flex/files/2102325/2016_Trips_Final_GIS.pdf)
[Dial_A_Ride_MAP.pdf](https://github.com/CUTR-at-USF/gtfs-flex/files/2102328/Dial_A_Ride_MAP.pdf)
