### ISSUE TITLE
How to define an area with a hole in the middle? Donuts!

### ISSUE THREAD

**Issue by antrim** [MobilityData/gtfs-flex#5]
via @mgilligan, from comment in [Google Doc](https://docs.google.com/document/d/1UTcpMJlANSoJ1ZEk5IrQh_plza1ZnvgwraMEBI_o2mw/edit?usp=sharing)

> How would one define an area with a hole in the middle? For example, the TriMet service benefit area has a hole in Happy Valley, OR. Maybe defining the points as part of an interior vs. exterior ring (similar to KML).

**Comment by antrim** [comment]
via @barbeau 

> Expanding on Mike's idea - a way of representing areas that would easily allow donuts would be:
> 
> * id - unique identifier
> * outer_boundary - encoded polyline for the external boundary of the area
> * inner_boundary - Field would be missing or empty for simple polygons, or the encoded polyline for the inner boundary of the donut, if representing a donut.
> 
> Polylines would be encoded using traditional polyline encoding algorithm (see https://developers.google.com/maps/documentation/utilities/polylinealgorithm and https://developers.google.com/maps/documentation/utilities/polylineutility). Using encoded polylines to represent lines would also reduce size/complexity of areas.txt files.

**Comment by antrim** [comment]
Another idea is from andrew@ridescout.com. Add areas.txt that contains the following fields: area_id, shape_id, type = [additive or subtractive].

**Comment by hbruch** [comment]
Why reinvent a new vector format as there exist some pretty standardized ones, like OGC-defined WKT? Most spatial databases support WKT as import format.

**Comment by barbeau** [comment]
Looking into this further, @hbruch has a good point.  OGC WKT format is probably the best option here for geometries, at least in terms of flexibility.

I backed into this conclusion - I was looking at the [GeoJSON spec](https://tools.ietf.org/html/rfc7946), which I think is probably the best way to represent this info in an API, and it says:

>GeoJSON comprises the seven concrete geometry types defined in the
   [OpenGIS Simple Features Implementation Specification for SQL [SFSQL]](https://tools.ietf.org/html/rfc7946#ref-SFSQL):
   0-dimensional Point and MultiPoint; 1-dimensional curve LineString
   and MultiLineString; 2-dimensional surface Polygon and MultiPolygon;
   and the heterogeneous GeometryCollection.  GeoJSON representations of
   instances of these geometry types are analogous to the well-known
   binary (WKB) and well-known text (WKT) representations described in
   that same specification.

[Here's a description](https://en.wikipedia.org/wiki/Well-known_text#Geometric_objects) of the WKT geometries, including some examples - here's a multi-polygon (i.e., with holes):

>MULTIPOLYGON (((40 40, 20 45, 45 30, 40 40)),
((20 35, 10 30, 10 10, 30 5, 45 20, 20 35),
(30 20, 20 15, 20 25, 30 20)))
>![image](https://cloud.githubusercontent.com/assets/928045/22487239/9b6fb634-e7da-11e6-96ca-7545a8f976d6.png)


Representing this in a CSV is a little messy (requires it be escaped with double quotes), but doable.

Any other thoughts on this?

**Comment by ed-g** [comment]
I agree, let's use WKT for the area geometry. 

WKT [allows spaces, tabs, and line feeds as white space](http://docs.opengeospatial.org/is/12-063r5/12-063r5.html#138), but I propose we restrict to only spaces, since GTFS [does not allow newlines or tabs](https://developers.google.com/transit/gtfs/reference/file-requirements)  even within quoted csv fields . 

Would this be too simple?

| Field Name | Required?  | Details |
|------------|------------|---------|
| area_id    | Required   | The **area_id** field contains an ID that uniquely identifies an area. |
| wkt        | Required   | <p> The **wkt** field contains a valid geometry in Open Geospatial Consortium Well Known Text format, with coordinates in the WGS-84 spatial reference system.</p> <p> In order to meet the GTFS file requirements, the **wkt** field must not contain line feeds, carriage returns, or tabs. </p> <p> Also, since the Well Known Text format itself uses commas, the **wkt** field will generally need to be double-quoted. </p> |

The only thing that concerns me is the WKT standard recommends that the [total length of a CRS WKT string not exceed 4096 characters](http://docs.opengeospatial.org/is/12-063r5/12-063r5.html#137).

Based on a quick experiment with PostGIS, each point of a multipolygon uses around 35 characters, which means we'd be limited to a maximum of approximately 117 points if we were to keep within the 4096 character limit.

Neither PostGIS, nor the [wellknown](https://github.com/mapbox/wellknown/blob/master/wellknown.js) javascript library enforce any character limit when parsing WKT. [GDAL](http://gdal.org/) doesn't appear to enforce any character limit either. I wonder if other WKT library implementations might.

Perhaps we should not specify a limit to the number of characters in the **wkt** field, but instead keep track of WKT size limits in any GIS libraries and tools we run across.

That way implementers can make educated decisions about the number of points to include in exported areas, and which GIS libraries to use.

**Comment by barbeau** [comment]
>Perhaps we should not specify a limit to the number of characters in the wkt field, but instead keep track of WKT size limits in any GIS libraries and tools we run across.

I agree - let's remain silent in our spec on length and allow WKT spec to speak for us. IMHO having a recommended limit is good, as I've seen some huge GTFS files with far too precise shapes.txt data.  WKT spec should hopefully encourage implementers to do some level of line simplification before writing the geometries.

**Comment by abyrd** [comment]
@ed-g said:
> The only thing that concerns me is the WKT standard recommends that the total length of a 
> CRS WKT string not exceed 4096 characters.

I think this restriction only applies to CRS (coordinate reference system) WKT strings. The document you linked to is called "Well-known text representation of coordinate reference systems". We'd only be allowing geometry WKT and the coordinate reference system would be fixed as WGS84.

I don't think there's any hard limit on the size of a WKT geometry.
