### ISSUE TITLE
Clarify `start_pickup_dropoff_window`/`end_pickup_dropoff_window` interpretation

### ISSUE THREAD

**Issue by gcamp** [MobilityData/gtfs-flex#62]
Currently it's unclear how `start_pickup_dropoff_window`/`end_pickup_dropoff_window ` should be interpreted since it affects both pickup and dropoff but the pickup and dropoff are not at the same time. 

For example, if `end_pickup_dropoff_window` is 21:00, can a user be picked up at 20:50 for a trip that is expected to last 20 minutes? 

Potential solution : 
A) Only support `start_pickup_window` and `end_pickup_window` and drop off is ignored. That would be my preferred option but it's possible it's not flexible enough for some producers. 
B) Support `start_pickup_window`/`end_pickup_window` and `start_drop_off_window`/`end_drop_off_window` 

Note : the name should also be `drop_off` and not `dropoff` to be consistant with the existing spec.

**Comment by scmcca** [comment]
I like solution B to allow for more granularity. It also gets rid of potentially inaccurate work-arounds to get close to actual drop-off cut off times using only one time frame for both concepts.

**Comment by scmcca** [comment]
Just to follow up on solution B, would `start_drop_off_window` actually be necessary? In a completely flexible service area, couldn't a rider technically get dropped off at anytime? And if not, something like minimum trip durations would have to live elsewhere as `start_drop_off_window` would only define that minimum trip duration for the first possible trip of the interval. 

Is there a use case for `start_drop_off_window` that I am missing?

Otherwise, I would advocate a **solution C** having 3 fields:
- `start_pickup_drop_off_window`
- `end_pickup_window`
- `end_drop_off_window`

Brainstorming the possible configurations:
1. `start_pickup_drop_off_window` AND `end_pickup_window`
     - This would be the most straightforward for processing allowed trip bookings based on the times prior to pickup in `booking_rules.txt`.
     - Example: If `end_pickup_window=16:00` and the rider must book their trip 30 minutes in advance, this would only be possible before 15:30.
2. `start_pickup_drop_off_window` AND `end_drop_off_window`
     - Calculating allowed trip bookings based on time prior to pickup requires some math. The consumer would have to:
          - (1) Calculate the estimated duration of the trip based on the O/D and other factors (i.e., ?real time traffic data) within the service area.
          - (2) Subtract the estimated duration from `end_drop_off_window` to infer an `end_pickup_window`.
          - (3) Subtract again the time prior needed for booking.
     - While this method looks messy, it would be interesting to know if agencies actually operate their service like this, and how they would estimate last pickup based on a particular trip when they only have a last drop off policy. If no one actually operates like this, we can scrap it.
3. `start_pickup_drop_off_window` AND `end_pickup_window` AND `end_drop_off_window`
     - Requiring all 3 fields is the most detailed account of an agencies pickup/dropoff time policy. 
     - Consumers would benefit from being able to easily calculate times prior required for booking using `start_pickup_drop_off_window` and `end_pickup_window` and be able to calculate last possible trips based on a defined (`end_pickup_window`, `end_drop_off_window`) interval without having to infer any additional information.
     - Even though agencies may not describe their service times in these 3 components, it allows them to be clear about their policy. 
          - Example 1: An agency that only defines `end_drop_off_window` in their policy can set their `end_pickup_window` to be equal. This would process any trips that alight after the `end_drop_off_window` to be invalid.
          - Example 2: An agency that only defines `end_pickup_window` in their policy would have to use some time sufficiently long enough in `end_drop_off_window` to capture the longest possible trip in the service area that would be calculated by a consumer. 

From the brainstorming it looks like solution C3 would be the most practical from a producer/consumer standpoint. Thoughts?

**Comment by westontrillium** [comment]
> Just to follow up on solution B, would start_drop_off_window actually be necessary? 

Huh, come to think of it, I don't think it would! An operator is not likely going to pick someone up and then drive them around, waiting for a drop-off window to begin; they would just take the passenger to their destination as soon as they boarded the vehicle (barring other passenger pickups).

> Is there a use case for start_drop_off_window that I am missing?

Not that is necessarily divorced from `start_pickup_drop_off_window`.

I think I agree with **solution C3**, however, `end_drop_off_window` should be an optional field, not a required one, since we'd need to be able to define a service in which a vehicle only picks up people in one area for a time and then shuttles them to drop off in another area:

trip_id | stop_id | stop_sequence | pickup_type | drop_off_type | start_pickup_drop_off_window | end_pickup_window | end_drop_off_window
----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- 
weekday | ZoneA | 1 | 2 | 1 | 08:00:00 | 09:00:00
weekday | ZoneB | 2 | 1 | 2 | 09:30:00 | | 10:30:00

**Comment by scmcca** [comment]
Right. To cover all cases we should write the conditionals for `end_pickup_window` dependent on `pickup_type≠1`, and `end_drop_off_window` dependent on `drop_off_type≠1`.

**Comment by gcamp** [comment]
What's the point of having `start_pickup_drop_off_window` if anyway we agree on the fact that the drop-off aspect are not useful? 

We should just not include `start_drop_off_window` and keep the rest. That would allow potentially somebody to ask for `start_drop_off_window` in the off chance they do without changing the existing values from the B proposal.

**Comment by westontrillium** [comment]
The start drop-off aspect is useful within the current spec for areas that are drop-off only.

If we went with @gcamp's on_demand_rules.txt proposal, I discovered a case in [this example](https://github.com/MobilityData/gtfs-flex/issues/54#issuecomment-906844763) that might require a separate `start_drop_off_window` field:

trip_id | stop_id | stop_sequence | pickup_type | drop_off_type | start_pickup_dropoff_window | end_pickup_dropoff_window 
| ------- | ------- | ------------- | ----------- | ------------- | --------------------------- | ------------------------- |
| 1           | zoneA   | 1                    | 2                  | 1               | 06:00:00                              | 09:00:00                  |
| **1**          |  **zoneB**   | **2**                    | **2**                  | **2**                     | **06:00:00**   | **21:00:00**        |
| **1**          |  **zoneA**   | **3**                     | **1**           | **2**                     | **18:00:00**                               | **21:00:00**                   |

Referencing the bolded lines: There is pickup and drop-off allowed within zoneB, and then drop-off opens up later to zoneA, but the drop-off window ends when the "main" zone's window ends.

I tried to model that with `on_demand_rules.txt` but was unsuccessful without using a `start_drop_off_window`:

route_id | from_id | to_id | service_id | start_pickup_window | end_pickup_window| start_drop_off_window | end_drop_off_window
-- | -- | -- | -- | -- | -- | -- | --
route | zoneB | zoneA | weekday | 06:00:00 | 21:00:00 | 18:00:00 | 21:00:00

**Comment by gcamp** [comment]
@westontrillium to be absolutely equivalent indeed it's not possible, but the point about it having no practical real value still stand. 

As you said yourself 

> An operator is not likely going to pick someone up and then drive them around, waiting for a drop-off window to begin

**Comment by westontrillium** [comment]
This issue has been resolved through discussion [here](https://github.com/google/transit/issues/336) and [here](https://github.com/google/transit/issues/335) and can be closed.
