### ISSUE TITLE
Allow points and multipoints in locations.geojson

### ISSUE THREAD

**Issue by scmcca** [MobilityData/gtfs-flex#63]
Is there a reason that points and multipoints are not an allowed geometry in locations.geojson? It seems like it would be useful to define a collection of stops as a multipoint instead of grouping predefined stops from stops.txt.

**Comment by scmcca** [comment]
> I don't know what the intention was for disallowing it, but I would guess it was to prevent the possibility of a single stop being represented in more than one datapoint/preventing more than one way to represent the same thing?

Can you elaborate how a `stop_id` and a point `locations.geojson` sharing the same coordinate would be consequential? Considering `stop_times.txt` spatial and temporal overlap rules previously described in [GOFS Phase 1](https://docs.google.com/document/d/1UJ21xWRzbG7Z3Xl-cpoYGoTmhRQv73XbttDoZ8bhGD8/edit#heading=h.vcl1cd8ol06u) (point 6), wouldn't this be okay? I.e., overlapping geometries occurring at non-conflicting times.

If there is a duplicated location with different (and false) information, this would be a data error and I think this could equally happen if we were only using `locations.geojson`.

>I don't see any huge issues with allowing points and multipoints though. I actually just came across a use case where that would be helpful because the pickup/drop-off points of the service weren't necessarily stops so much as literal locations the service will pickup/drop-off (e.g. a point at each curb cut).

FWIW I don't necessarily see this as a conceptual advantage more than it is a way to package data. The official GTFS reference defines records in `stops.txt` as "locations" rather than strict "stops". Furthermore, the [definition](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#stopstxt) for a "stop" (`location_type=0' or blank) is compatible with "locations the service will pickup/drop-off" passengers:
> A location where passengers board or disembark from a transit vehicle.

So I think it's fair game whether a data producer defines single point stops in `stops.txt` and groups them in `location_groups.txt`, or chooses to be perhaps more efficient when describing a group of points using a single multipoint feature in `locations.geojson`.

Thoughts?

**Comment by westontrillium** [comment]
> Can you elaborate how a `stop_id` and a point `locations.geojson` sharing the same coordinate would be consequential?

I guess it's only consequential if they shared the same id value, as a consumer wouldn't know which to reference. So as long as we added a note about forbidding matching ids, it would be fine. And yes, assuming it follows the GOFS spatial and temporal overlap rules. 🙂

> So I think it's fair game whether a data producer defines single point stops in `stops.txt` and groups them in `location_groups.txt`, or chooses to be perhaps more efficient when describing a group of points using a single multipoint feature in `locations.geojson`.

Agreed. I imagine the primary use case for using a multipoint feature would be to define unordered pickup/drop-off locations that _aren't_ serviced in other fixed routes since there would be no advantage in having them also live in `stops.txt`. Using `stops.txt` stops grouped in `location_groups.txt` would be for that use case of grabbing the already-existing, applicable fixed-route stops for such a service (like an eligibility-based dial-a-ride that travels to any stop in any order, operating in tandem with the fixed-route service).
