### ISSUE TITLE
Discussion/open question: Backward compatibility with GTFS?

### ISSUE THREAD

**Issue by antrim** [MobilityData/gtfs-flex#9]
We aspire toward backward compatibility with GTFS. How feasible is that? In what circumstances might it make sense to give that up, and how would that be managed?

Open thread for discussion and reference.

**Comment by hbruch** [comment]
GTFS-flex should be as backward compatible as possible, to allow smooth transition for existing applications, perhaps use case per use case. 

However, how do you define 'backward compatibility' for CSV files? I'd say:

- existing file names should not change 
- new files should be optional
- column names should not change
- new columns should be optional
- formats for existing columns should not change

Still another question: are csv-files the right format for flexible data, which presumably will not be delivered as a static batch of data but event based, record by record?

**Comment by abyrd** [comment]
I'm generally in favor of the backward compatibility requirement in GTFS. To the extent that entities defined in standard GTFS are suitable (e.g. stops) those tables should be re-used with a few additional optional columns. That said, for flex service full (bidirectional) backward compatibility may not be appropriate. 

As analog examples of backward compatibility, take stereo FM radio or color TV. A mono signal can be played on a stereo receiver, and (importantly) a stereo signal can be played on a mono receiver that was built before the stereo spec even existed. Likewise a black-and-white signal could be displayed on a color TV, and (importantly) a color signal could be displayed on a black and white TV that predated the color spec.

Some GTFS extensions allow extended data sets to be interpreted by older systems, providing the same quality of information as the pre-extension GTFS did on those older systems. The new data is just ignored as if it wasn't there, and the old data remains valid in the absence of the new. 

This is not the case with flex services. For example, if trips.txt and stop_times.txt are used to define a service where most or all stops are unordered and must be requested, an existing system that does not know about the extension fields will interpret this as an ordered trip and happily give customers very incorrect information, with no indication to the end user or even to the people writing/running the consumer software that something is wrong.

Ideally we want old systems to either ignore / not see the new data at all, or see it as erroneous as a red flag to the consumer. Features of the existing base GTFS system would be used to ensure that rather than being misinterpreted, information would be harmlessly discarded or highlighted.

This could be an argument in favor of using completely new txt files to define the flex services, such that an existing consumer would just see orphaned stops and stop times that are curiously not organized into routable trips.

**Comment by abyrd** [comment]
@hbruch said:
> Still another question: are csv-files the right format for flexible data, which presumably will not be 
> delivered as a static batch of data but event based, record by record?

As far as I know this spec has been designed as static data, describing stable services offered over the long term. I don't think it was intended to include any event-based data. 

I think we may need to clarify the purpose of this specification in the Readme, saying what it is and is not. Here and on the mailing list some people seem to interpret it as a real-time data set describing minute-to-minute operations of a TNC-type operator, or an API allowing reservations or dynamic location queries.

**Comment by abyrd** [comment]
One way to mostly reuse existing tables and fields, but make the data appear invalid, raise red flags and prevent older consumers from misinterpreting it, is to express unordered stops within trips by repeating the same stop sequence number for those stops. I opened another ticket for this (#36).


Our three main choices are:
1. Reuse as many tables as possible, but legacy systems will misinform riders.
2. Intentionally make flex tables violate existing rules, so legacy systems realize they don't understand the data and refuse to consume it.
3. Put flex data in totally new tables so legacy systems won't see it at all, and can still consume the classic scheduled service within the same feed.

**Comment by t2gran** [comment]
Making new files and columns _optional_ to be backward compatible is not ideal. If the nature of such files and columns is that they should be required they should be so. When implementing the new version the system should give a warning for such errors if possible, then later when the old format is not supported any more the system can be changed to fail such input.

**Comment by abyrd** [comment]
@t2gran there is a nuance here: some files or fields may be required when flex data is included in the feed. But the entire set of flex extensions is optional, because no GTFS feed is required to contain flex data. So if the Flex specification contains some "required" fields, this is a new hierarchical kind of "required".
